name: Java CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      working-directory: ./build
      run: |
        sed -i 's#<input .*/>##' build.xml
        ant clean dist
    - name: Install X virtual framebuffer
      run: sudo apt-get install -y xvfb
    - name: Run tests
      working-directory: ./app
      run: xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" ant test -Drunning-from-github-action=1
    - name: Publish results
      uses: actions/upload-artifact@v1
      with:
        name: html-results
        path: app/test-bin/results/html/
    - name: Cleanup xvfb
      uses: bcomnes/cleanup-xvfb@v1
